use daolab;
CREATE TABLE MOCK_DATA(id int, first_name VARCHAR(20), last_name VARCHAR(20), email VARCHAR(20), gender VARCHAR(20), city VARCHAR(20));
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (1, 'Sharleen', 'Gillbard', 'sgillbard0@cargocollective.com', 'Female', 'Dragomer');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (2, 'Calhoun', 'Frostdyke', 'cfrostdyke1@marketwatch.com', 'Male', 'Xinjian');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (3, 'Noble', 'Borgnol', 'nborgnol2@clickbank.net', 'Male', 'Renfengzhuang');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (4, 'Candace', 'Legging', 'clegging3@usda.gov', 'Female', 'Novaya Mayna');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (5, 'Christalle', 'Savell', 'csavell4@dmoz.org', 'Female', 'Baku');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (6, 'Sherm', 'O''Dyvoie', 'sodyvoie5@admin.ch', 'Male', 'Port Said');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (7, 'Zebulon', 'Lesaunier', 'zlesaunier6@icq.com', 'Male', 'Adelaide');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (8, 'Adrian', 'Bockett', 'abockett7@stanford.edu', 'Male', 'Grängesberg');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (9, 'Zachery', 'Zanolli', 'zzanolli8@eepurl.com', 'Male', 'Abiko');
insert into MOCK_DATA (id, first_name, last_name, email, gender, city) values (10, 'Ben', 'Hurleston', 'bhurleston9@oakley.com', 'Male', 'Jiuting');
